apiVersion: v1
kind: Service
metadata:
    name: config-server
    labels:
        app: config-server
        tier: backend
spec:
    type: NodePort
    ports:
    - port: 8888
    selector:
        app: config-server
        tier: backend